PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPTW {
   Configurations {
    EntityPersistenceConfig "{E3FF82064D3A4188}" : "{F97CF9B77FFA8839}Configs/Systems/Persistence/Configuration/EXPTW/WeatherTransition.conf" {
     Collection "{6624C4351F719B74}"
    }
    EntityPersistenceConfig "{8C41F2CD06375154}" : "{0820F39B560EADFC}Configs/Systems/Persistence/Configuration/EXPTW/TimeSkip.conf" {
     Collection "{6624C4351F719B74}"
    }
   }
  }
 }
}
