PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPG {
   Configurations {
    StatePersistenceConfig "{EC6D1374EB2F7B88}" {
     Collection "{6586D01E488CA578}"
     SelfDelete 0
     Serializer EXPG_GarrisonPersistenceSerializer "{0B42DF0C9043AF87}" {
     }
    }
   }
  }
 }
 PersistentStates + {
  EXPG_GarrisonPersistenceState "{E5544205F97A2B93}" {
  }
 }
}
