PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPBG {
   Configurations {
    EntityPersistenceConfig "{E4871A3B6F8D4021}" : "{DBEC4D5170634E86}Configs/Systems/Persistence/Configuration/EXPBG/CacheZone.conf" {
     Collection "{6624C4351F719B74}"
    }
    StatePersistenceConfig "{7C9059048B12E63A}" {
     Collection "{6586D01E488CA578}"
     SelfDelete 0
     Serializer EBG_MissionPersistenceSerializer "{D637A051F94C28BE}" {
     }
    }
   }
  }
 }
 PersistentStates + {
  EBG_MissionPersistenceState "{A5E391D827CB604F}" {
  }
 }
}
