// Generated by tools/audio/generate_bank.py; edit docs/audio-assets.json.
class EAS_Bank
{
 static const ResourceName PROJECT = "{F078863A97562BB2}Audio/EXPBG/AmbientSounds/EXPBG_AmbientSounds.acp";
 static array<ref EAS_Clip> Create()
 {
  array<ref EAS_Clip> bank = {};
  bank.Insert(new EAS_Clip("SOUND_EAS_CZ_SHORT", 1.6600000, 0, 1, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_CZ_DENSE", 2.4000000, 0, 2, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_EXPLOSION_LOGDRUM", 5.1428750, 1, 0, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_EXPLOSION_NOISE", 7.8019167, 1, 0, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_EXPLOSION_WOOD", 5.4031667, 1, 0, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("EAS_Jet_Flyby1", 24.2925833, 2, 0, 0, 1, 1.0000000));
  bank.Insert(new EAS_Clip("EAS_Jet_Flyby2", 63.5083542, 2, 0, 0, 2, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_AK762_DISTANT", 1.4479819, 0, 0, 0, 0, 0.3548350));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_AK762_FAR", 1.5720408, 0, 0, 0, 0, 0.3608369));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_AR556_DISTANT", 1.5034921, 0, 0, 0, 0, 0.3548350));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_AR556_FAR", 1.4415420, 0, 0, 0, 0, 0.5431940));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_LMG762_DISTANT", 1.5843764, 0, 0, 0, 0, 0.3548675));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_LMG762_FAR", 1.5905442, 0, 0, 0, 0, 0.3548567));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_DSHK_DISTANT", 2.1977778, 0, 0, 0, 0, 0.4192307));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_DSHK_FAR", 3.9163039, 0, 0, 0, 0, 0.3548459));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_GRENADE_DISTANT", 3.0840136, 1, 0, 0, 0, 0.3548350));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_GRENADE_FAR", 3.0840136, 1, 0, 0, 0, 0.8134988));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_ROCKET_DISTANT", 4.9626077, 1, 0, 0, 0, 0.3548350));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_ROCKET_FAR", 5.2097506, 1, 0, 0, 0, 0.4191098));
  bank.Insert(new EAS_Clip("SOUND_EAS_WARMIX_GUNFIRE1", 600.0036250, 3, 0, 0, 1, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_WARMIX_GUNFIRE2", 600.0024583, 3, 0, 0, 2, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_WARMIX_OUTPOST", 1841.0173333, 3, 0, 0, 3, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_FIREFIGHT_NEAR", 188.0190000, 0, 0, 1, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_FIREFIGHT_DISTANT", 195.0080000, 0, 0, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_SHELLING_DISTANT", 131.1770833, 1, 0, 0, 0, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_WARMIX_KENT", 68.8199167, 3, 0, 0, 4, 1.0000000));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_GRENADE_NEAR", 4.2135828, 1, 0, 1, 0, 0.3548350));
  bank.Insert(new EAS_Clip("SOUND_EAS_JSRS_ROCKET_NEAR", 3.1808163, 1, 0, 1, 0, 0.3548350));
  return bank;
 }
}
