// Generated by tools/audio/generate_radio.py; recording IDs are permanent.
class EAS_RadioBank
{
 static const ResourceName PROJECT = "{927186ED2C764ED2}Audio/EXPBG/AmbientSounds/EXPBG_Radio.acp";
 static string Event(int recording)
 {
  switch (recording)
  {
   case 0: return "EAS_Radio_Static";
   case 1: return "EAS_Radio_Apache1";
   case 2: return "EAS_Radio_Apache2";
   case 3: return "EAS_Radio_Russian1";
   case 4: return "EAS_Radio_Russian2";
   case 5: return "EAS_Radio_Russian3";
   case 6: return "EAS_Radio_Russian4";
   case 7: return "EAS_Radio_Chinese1";
   case 8: return "EAS_Radio_ArabChatter";
   case 9: return "EAS_Radio_Arab1";
   case 10: return "SOUND_EAS_RADIO_BATTLEFIELD3";
   case 11: return "SOUND_EAS_RADIO_MYSTERYRUSSIAN";
   case 12: return "SOUND_EAS_RADIO_RUSSIANCHATTER";
  }
  return "";
 }
 static float Duration(int recording)
 {
  switch (recording)
  {
   case 0: return 18.7181042;
   case 1: return 230.2490625;
   case 2: return 177.7066667;
   case 3: return 241.7893958;
   case 4: return 139.8073542;
   case 5: return 263.4071667;
   case 6: return 240.5819583;
   case 7: return 331.1397708;
   case 8: return 70.2403542;
   case 9: return 75.4880625;
   case 10: return 503.0139167;
   case 11: return 178.0041667;
   case 12: return 607.0160833;
  }
  return 0;
 }
 static bool ValidSelection(int selection)
 {
  if (!Event(selection).IsEmpty()) return true;
  return selection == 100 || selection == 101 || selection == 102 || selection == 103;
 }
 static int Resolve(int selection, int previous)
 {
  if (!Event(selection).IsEmpty()) return selection;
  switch (selection)
  {
   case 100: return EAS_RadioBank.Pick({3, 4, 5, 6, 11, 12}, previous);
   case 101: return EAS_RadioBank.Pick({1, 2, 10}, previous);
   case 102: return EAS_RadioBank.Pick({7}, previous);
   case 103: return EAS_RadioBank.Pick({8, 9}, previous);
  }
  return -1;
 }
 // One bounded native draw; skip the last completed choice when alternatives exist.
 static int Pick(array<int> candidates, int previous)
 {
  if (!candidates || candidates.IsEmpty()) return -1;
  array<int> choices = {};
  foreach (int candidate : candidates)
   if (candidate != previous || candidates.Count() == 1) choices.Insert(candidate);
  if (choices.IsEmpty()) return -1;
  return choices[Math.RandomInt(0, choices.Count())];
 }
}
