// Generated by tools/audio/generate_radio.py; recording IDs are permanent.
class EAS_TVBank
{
 static const ResourceName PROJECT = "{927186ED2C764ED2}Audio/EXPBG/AmbientSounds/EXPBG_Radio.acp";
 static string Event(int recording)
 {
  switch (recording)
  {
   case 0: return "SOUND_EAS_EMERGENCYALERT";
  }
  return "";
 }
 static float Duration(int recording)
 {
  switch (recording)
  {
   case 0: return 21.5713333;
  }
  return 0;
 }
 static bool ValidSelection(int selection)
 {
  if (!Event(selection).IsEmpty()) return true;
  return false;
 }
 static int Resolve(int selection, int previous)
 {
  if (!Event(selection).IsEmpty()) return selection;
  return -1;
 }
}
