// Generated by tools/audio/generate_radio.py; recording IDs are permanent.
class EAS_CrowdBank
{
 static const ResourceName PROJECT = "{927186ED2C764ED2}Audio/EXPBG/AmbientSounds/EXPBG_Radio.acp";
 static string Event(int recording, int range = 60)
 {
  if (range < 10 || range > 150 || range % 10 != 0) return "";
  switch (recording)
  {
   case 0: return "SOUND_EAS_CROWD_ANGRY" + "_R" + range.ToString();
   case 1: return "SOUND_EAS_CROWD_TALKING" + "_R" + range.ToString();
   case 2: return "SOUND_EAS_CROWD_DOWNTOWN" + "_R" + range.ToString();
   case 3: return "SOUND_EAS_CROWD_LARGE" + "_R" + range.ToString();
  }
  return "";
 }
 static float Duration(int recording)
 {
  switch (recording)
  {
   case 0: return 31.7280000;
   case 1: return 59.7432917;
   case 2: return 120.0930000;
   case 3: return 180.0000000;
  }
  return 0;
 }
 static bool ValidSelection(int selection)
 {
  if (!Event(selection).IsEmpty()) return true;
  return selection == 100;
 }
 static int Resolve(int selection, int previous)
 {
  if (!Event(selection).IsEmpty()) return selection;
  switch (selection)
  {
   case 100: return EAS_RadioBank.Pick({0, 1, 2, 3}, previous);
  }
  return -1;
 }
}
