SCR_PlaceableEntitiesRegistry {
 m_Prefabs + {
  "{B8EE906EA1B549D5}PrefabsEditable/EXPBG/E_EXPBG_AmbientSounds.et"
  "{A52B74971E17499E}PrefabsEditable/EXPBG/E_EXPBG_Radio_Black.et"
  "{5D3FFD5826E8A488}PrefabsEditable/EXPBG/E_EXPBG_Radio_ANGRC160.et"
  "{C6F32100C9F59391}PrefabsEditable/EXPBG/E_EXPBG_Radio_R123M.et"
  "{39BE2B7569C94215}PrefabsEditable/EXPBG/Crowd/E_EXPBG_Crowd.et"
  "{218B74863A034D48}PrefabsEditable/EXPBG/SoundEffects/E_EXPBG_TV.et"
 }
}
