SCR_PlaceableEntitiesRegistry {
 m_Prefabs + {
  "{B8EE906EA1B549D5}PrefabsEditable/EXPBG/E_EXPBG_AmbientSounds.et"
  "{A52B74971E17499E}PrefabsEditable/EXPBG/E_EXPBG_Radio_Black.et"
  "{5D3FFD5826E8A488}PrefabsEditable/EXPBG/E_EXPBG_Radio_ANGRC160.et"
  "{C6F32100C9F59391}PrefabsEditable/EXPBG/E_EXPBG_Radio_R123M.et"
  "{39BE2B7569C94215}PrefabsEditable/EXPBG/Crowd/E_EXPBG_Crowd.et"
  "{218B74863A034D48}PrefabsEditable/EXPBG/SoundEffects/E_EXPBG_TV.et"
  "{9D00F49669BABA9B}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_RadioStatic.et"
  "{E6539A48EB19A712}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Apache1.et"
  "{9377318575819591}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Apache2.et"
  "{AB95F30767C1E2D0}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Russian1.et"
  "{F0A4B56AB63A3358}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Russian2.et"
  "{8EB46CB9B1A568F9}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Russian3.et"
  "{2A92FEDFEA4F6E39}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Russian4.et"
  "{D4E73532E77EB129}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Chinese1.et"
  "{9F5A7829E724A889}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_ArabChatter.et"
  "{F9C887DD4A58A192}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Arab1.et"
  "{B5DF6B1C85E501C5}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_HanoiHannah.et"
  "{6600A4429C2D5951}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_CloseFirefight.et"
  "{B88DDF214D5356B8}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_DistantFirefight.et"
  "{1DA9472AF532B605}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_DistantShelling.et"
  "{364516356EE87F8E}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_JetFlyby1.et"
  "{432CD5C1C1314DE1}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_JetFlyby2.et"
  "{7D0AA014F7814C40}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_DroneOverhead.et"
  "{AF51EA5F8711DC50}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_Market.et"
  "{5BF43F4DC8036F95}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_MarketSeller.et"
  "{56FABC565B0382F9}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_StreetSinging.et"
  "{7A7123F37E3C40EC}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_MuslimPrayer.et"
  "{A39488EB7FCC37AA}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_TrafficMedium.et"
  "{C9FB6FAB042F19FE}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_ChurchBell.et"
  "{38B10DE143D7A0C6}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_CarAlarm.et"
  "{96D33B7A9301A353}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_PoliceCar.et"
  "{21E6A8BD0DAF021D}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_NokiaRingtone.et"
  "{E8514C7DB73C2CD5}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_DistantBarking.et"
  "{328C5063BC0D9CFD}PrefabsEditable/EXPBG/Sounds/E_EXPBG_Sound_DistantSheep.et"
 }
}
