EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{CF931BA4ACB0BB71}" {
  EntityClass "ETW_WeatherModule"
 }
 Priority 20000
 ParentHandling "Ignore always"
 EntitySerializer ETW_WeatherModuleSerializer "{080E88DCA8D2279C}" {
 }
}
