EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{2425E09954530DD9}" {
  EntityClass "EXPG_RandomGarrisonModule"
 }
 Priority 20001
 ParentHandling "Ignore always"
 EntitySerializer EXPG_RandomGarrisonSerializer "{DAC41CE937AF2E11}" {
 }
}
