PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPAU {
   Configurations {
    EntityPersistenceConfig "{C32A76C5FE95E688}" : "{8FAD2070A07A0934}Configs/Systems/Persistence/Configuration/EXPAU/ProtestZone.conf" {
     Collection "{6624C4351F719B74}"
    }
   }
  }
 }
}
