EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{C39008B425CA49DF}" {
  EntityClass "EBG_CacheZone"
 }
 Priority 20000
 ParentHandling "Ignore always"
 EntitySerializer EBG_CacheZoneSerializer "{BCA4E71F69D348F2}" {
 }
}
