SCR_PlaceableEntitiesRegistry {
 m_Prefabs + {
  "{D3DCA7AB761413C6}PrefabsEditable/EXPII/EII_ManualUS.et"
  "{7E8D916D8F449094}PrefabsEditable/EXPII/EII_ManualSoviet.et"
  "{23BD5CC4A9B2CC83}PrefabsEditable/EXPII/EII_NotebookBlue.et"
  "{4940337955AE3340}PrefabsEditable/EXPII/EII_NotebookBlack.et"
  "{9AA03E7756B80823}PrefabsEditable/EXPII/EII_NotebookOrange.et"
  "{46DA23F715D50DAB}PrefabsEditable/EXPII/EII_ArmoredLaptop.et"
  "{1B3F61C4291552DE}PrefabsEditable/EXPII/EII_Tablet2.et"
 }
}
