StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{B50153A8FF73AF04}" {
   Id "EII-ManualUS_Name"
   Target_en_us "EXPBG Intel - US Field Manual"
  }
  CustomStringTableItem "{FCF81160563E2E35}" {
   Id "EII-ManualUS_InventoryName"
   Target_en_us "Intel - US Field Manual"
  }
  CustomStringTableItem "{13577BEDD5B3DC0D}" {
   Id "EII-ManualSoviet_Name"
   Target_en_us "EXPBG Intel - Soviet Field Manual"
  }
  CustomStringTableItem "{51AD0147D13EF5A6}" {
   Id "EII-ManualSoviet_InventoryName"
   Target_en_us "Intel - Soviet Field Manual"
  }
  CustomStringTableItem "{14DC0407A028A4AF}" {
   Id "EII-NotebookBlue_Name"
   Target_en_us "EXPBG Intel - Blue Notebook"
  }
  CustomStringTableItem "{F36C00469B28B771}" {
   Id "EII-NotebookBlue_InventoryName"
   Target_en_us "Intel - Blue Notebook"
  }
  CustomStringTableItem "{26E83AAB8B6ADB6C}" {
   Id "EII-NotebookBlack_Name"
   Target_en_us "EXPBG Intel - Black Notebook"
  }
  CustomStringTableItem "{7303F570AA5C41EE}" {
   Id "EII-NotebookBlack_InventoryName"
   Target_en_us "Intel - Black Notebook"
  }
  CustomStringTableItem "{A024A18726C98BF3}" {
   Id "EII-NotebookOrange_Name"
   Target_en_us "EXPBG Intel - Orange Notebook"
  }
  CustomStringTableItem "{E9ED67DCAC776A20}" {
   Id "EII-NotebookOrange_InventoryName"
   Target_en_us "Intel - Orange Notebook"
  }
  CustomStringTableItem "{B7093D19705250B2}" {
   Id "EII-ArmoredLaptop_Name"
   Target_en_us "EXPBG Intel - Armored Laptop"
  }
  CustomStringTableItem "{F3C0604866F6F1E5}" {
   Id "EII-ArmoredLaptop_InventoryName"
   Target_en_us "Intel - Armored Laptop"
  }
  CustomStringTableItem "{2BF08F3065AAB5AA}" {
   Id "EII-Tablet2_Name"
   Target_en_us "EXPBG Intel - Tablet 2"
  }
  CustomStringTableItem "{CBAA53CE8DE014EE}" {
   Id "EII-Tablet2_InventoryName"
   Target_en_us "Intel - Tablet 2"
  }
  CustomStringTableItem "{CF2D1055C281DBD1}" {
   Id "EII-Intel_Name"
   Target_en_us "EXPBG Intel"
  }
  CustomStringTableItem "{DF91A10DB31CC495}" {
   Id "EII-IntelItems_Name"
   Target_en_us "EXPBG Intel Items"
  }
 }
}
