SCR_EditorContentBrowserDisplayConfig {
 m_sContentBrowserHeader "Choose Garrison Squad"
 m_bSaveContentBrowserState 0
 m_aWhiteListLabelGroups {
  SCR_EditorContentBrowserDisplayGroupLabel "{FB90726463F34532}" {
   m_iGroupLabel FACTION
  }
  SCR_EditorContentBrowserDisplayGroupLabel "{4EED7C205CA34FD9}" {
   m_iGroupLabel GROUPSIZE
  }
  SCR_EditorContentBrowserDisplayGroupLabel "{3F379B08FB2847CB}" {
   m_iGroupLabel CONTENT
  }
 }
 m_aAlwaysActiveLabels {
  SCR_EditorContentBrowserActiveDisplayLabel "{5A17ABF6CC734DA3}" {
   m_iLabel ENTITYTYPE_GROUP
  }
  SCR_EditorContentBrowserActiveDisplayLabel "{5F5C7DCE00C34B66}" {
   m_iLabel GROUPTYPE_INFANTRY
  }
 }
}
