PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPUD {
   Configurations {
    StatePersistenceConfig "{728D0F16A5484277}" {
     Collection "{6586D01E488CA578}"
     SelfDelete 0
     Serializer EUD_DialogPersistenceSerializer "{910312904B57D552}" {
     }
    }
   }
  }
 }
 PersistentStates + {
  EUD_DialogPersistenceState "{17FD3FD686C990D8}" {
  }
 }
}
