StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{4C063566D196443B}" {
   Id "EAS-War_Name"
   Target_en_us "EXPBG Ambient War Module"
  }
  CustomStringTableItem "{1AABE502830C4B58}" {
   Id "EAS-Crowd_Name"
   Target_en_us "EXPBG Ambient Crowd Sound"
  }
  CustomStringTableItem "{5BA8EBB7E8AD4305}" {
   Id "EAS-RadioBlack_Name"
   Target_en_us "EXPBG Radio Black"
  }
  CustomStringTableItem "{4592CF209D984037}" {
   Id "EAS-RadioRed_Name"
   Target_en_us "EXPBG Radio Red"
  }
  CustomStringTableItem "{240F8EEA8B564F10}" {
   Id "EAS-RadioANGRC160_Name"
   Target_en_us "EXPBG Radio AN/GRC-160"
  }
  CustomStringTableItem "{E23CB37FBD7A49A1}" {
   Id "EAS-RadioR123M_Name"
   Target_en_us "EXPBG Radio R123M"
  }
  CustomStringTableItem "{17E51FD230564396}" {
   Id "EAS-TV_Name"
   Target_en_us "EXPBG Emergency Alert TV"
  }
  CustomStringTableItem "{F99E5FC5EF7FB4BF}" {
   Id "EAS-SoundRadioStatic_Name"
   Target_en_us "EXPBG Sound: Radio static"
  }
  CustomStringTableItem "{8B81BBD7EB3E168C}" {
   Id "EAS-SoundApache1_Name"
   Target_en_us "EXPBG Sound: Apache chatter 1"
  }
  CustomStringTableItem "{28D13D3E7FCFC500}" {
   Id "EAS-SoundApache2_Name"
   Target_en_us "EXPBG Sound: Apache chatter 2"
  }
  CustomStringTableItem "{5A235F75B35F97E5}" {
   Id "EAS-SoundRussian1_Name"
   Target_en_us "EXPBG Sound: Russian radio 1"
  }
  CustomStringTableItem "{C7CFD9E9269A678B}" {
   Id "EAS-SoundRussian2_Name"
   Target_en_us "EXPBG Sound: Russian radio 2"
  }
  CustomStringTableItem "{8B96B0D99A0E0412}" {
   Id "EAS-SoundRussian3_Name"
   Target_en_us "EXPBG Sound: Russian radio 3"
  }
  CustomStringTableItem "{AEEDE7874C260D03}" {
   Id "EAS-SoundRussian4_Name"
   Target_en_us "EXPBG Sound: Russian radio 4"
  }
  CustomStringTableItem "{8C59BCD26E34F436}" {
   Id "EAS-SoundChinese1_Name"
   Target_en_us "EXPBG Sound: Chinese radio 1"
  }
  CustomStringTableItem "{1758F736AE7D0E6B}" {
   Id "EAS-SoundArabChatter_Name"
   Target_en_us "EXPBG Sound: Arab radio chatter"
  }
  CustomStringTableItem "{FCB1D2A689B72EC7}" {
   Id "EAS-SoundArab1_Name"
   Target_en_us "EXPBG Sound: Arab radio"
  }
  CustomStringTableItem "{A5381E4AAFDE0F62}" {
   Id "EAS-SoundHanoiHannah_Name"
   Target_en_us "EXPBG Sound: Hanoi Hannah broadcast"
  }
  CustomStringTableItem "{94D76298BFFE4EDE}" {
   Id "EAS-SoundCloseFirefight_Name"
   Target_en_us "EXPBG Sound: Close firefight"
  }
  CustomStringTableItem "{6DB71F6680B8590A}" {
   Id "EAS-SoundDistantFirefight_Name"
   Target_en_us "EXPBG Sound: Distant firefight (1.5 km)"
  }
  CustomStringTableItem "{7B38A3D2E0807225}" {
   Id "EAS-SoundDistantShelling_Name"
   Target_en_us "EXPBG Sound: Distant shelling"
  }
  CustomStringTableItem "{266A186EDDBDA205}" {
   Id "EAS-SoundJetFlyby1_Name"
   Target_en_us "EXPBG Sound: Jet flyby 1"
  }
  CustomStringTableItem "{19EBBDFDC2582AC5}" {
   Id "EAS-SoundJetFlyby2_Name"
   Target_en_us "EXPBG Sound: Jet flyby 2"
  }
  CustomStringTableItem "{248FA8E426C6BC2F}" {
   Id "EAS-SoundDroneOverhead_Name"
   Target_en_us "EXPBG Sound: Drone overhead"
  }
  CustomStringTableItem "{4914E4E2590AFC35}" {
   Id "EAS-SoundMarket_Name"
   Target_en_us "EXPBG Sound: Market ambience"
  }
  CustomStringTableItem "{2A4BEB8916B6D121}" {
   Id "EAS-SoundMarketSeller_Name"
   Target_en_us "EXPBG Sound: Market seller"
  }
  CustomStringTableItem "{95F3C1C8C4588D64}" {
   Id "EAS-SoundStreetSinging_Name"
   Target_en_us "EXPBG Sound: Street singing"
  }
  CustomStringTableItem "{3BDC03E76DEB9FE2}" {
   Id "EAS-SoundMuslimPrayer_Name"
   Target_en_us "EXPBG Sound: Muslim prayer"
  }
  CustomStringTableItem "{3E1D00A7F25A5157}" {
   Id "EAS-SoundTrafficMedium_Name"
   Target_en_us "EXPBG Sound: Traffic (medium distance)"
  }
  CustomStringTableItem "{AA7B7DA1340C7433}" {
   Id "EAS-SoundChurchBell_Name"
   Target_en_us "EXPBG Sound: Church bell"
  }
  CustomStringTableItem "{CAFD6B36AF282A86}" {
   Id "EAS-SoundCarAlarm_Name"
   Target_en_us "EXPBG Sound: Car alarm"
  }
  CustomStringTableItem "{F1CB6501C8ADBCD6}" {
   Id "EAS-SoundPoliceCar_Name"
   Target_en_us "EXPBG Sound: Police car"
  }
  CustomStringTableItem "{E4F0D0D28039ACD6}" {
   Id "EAS-SoundNokiaRingtone_Name"
   Target_en_us "EXPBG Sound: Nokia ringtone"
  }
  CustomStringTableItem "{D1177D8DDCE9E875}" {
   Id "EAS-SoundDistantBarking_Name"
   Target_en_us "EXPBG Sound: Distant barking"
  }
  CustomStringTableItem "{C866FA7CAA90A13D}" {
   Id "EAS-SoundDistantSheep_Name"
   Target_en_us "EXPBG Sound: Distant sheep"
  }
 }
}
