StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{4C063566D196443B}" {
   Id "EAS-War_Name"
   Target_en_us "EXPBG Ambient War Module"
  }
  CustomStringTableItem "{1AABE502830C4B58}" {
   Id "EAS-Crowd_Name"
   Target_en_us "EXPBG Crowd Module"
  }
  CustomStringTableItem "{5BA8EBB7E8AD4305}" {
   Id "EAS-RadioBlack_Name"
   Target_en_us "EXPBG Radio Black"
  }
  CustomStringTableItem "{4592CF209D984037}" {
   Id "EAS-RadioRed_Name"
   Target_en_us "EXPBG Radio Red"
  }
  CustomStringTableItem "{240F8EEA8B564F10}" {
   Id "EAS-RadioANGRC160_Name"
   Target_en_us "EXPBG Radio AN/GRC-160"
  }
  CustomStringTableItem "{E23CB37FBD7A49A1}" {
   Id "EAS-RadioR123M_Name"
   Target_en_us "EXPBG Radio R123M"
  }
  CustomStringTableItem "{17E51FD230564396}" {
   Id "EAS-TV_Name"
   Target_en_us "EXPBG Emergency Alert TV"
  }
 }
}
