EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{6F8CC7470E5278C8}" {
  EntityClass "ESR_SurrenderModule"
 }
 Priority 20000
 ParentHandling "Ignore always"
 EntitySerializer ESR_SurrenderModuleSerializer "{C9A5CE17CD518B03}" {
 }
}
