SCR_EditorActionList {
 m_Actions {
  EXPG_AddGarrisonContextAction "{B8B4BC59FA904E70}" {
   m_Info SCR_UIInfo "{14A891122FEC4B71}" {
    Name "EXPBG Add Garrison"
    Description "Choose an infantry squad to occupy this building."
    Icon "{21BAFC03CB14EAD3}UI/Textures/Editor/ContextMenu/ContextAction_BaseSupply.edds"
   }
   m_iOrder 205
   m_bIsServer 0
   m_Browser SCR_EditorContentBrowserDisplayConfig "{F5E92569ABAB4A63}" : "{A67E2D7288844EAF}Configs/Editor/ContentBrowser/EXPG_Infantry.conf" {
   }
  }
  EXPG_ReleaseAllGarrisonsContextAction "{25D3FA69E5E74FFB}" {
   m_Info SCR_UIInfo "{3F7E1485F0D465DB}" {
    Name "EXPBG Release All Garrisons"
    Description "Wake every garrison and return all garrison squads to normal AI control. Garrisons are saved with the mission; use this only before removing EXPBG GM Tools from a mission."
    Icon "{21BAFC03CB14EAD3}UI/Textures/Editor/ContextMenu/ContextAction_BaseSupply.edds"
   }
   m_iOrder 206
   m_bIsServer 1
  }
 }
}
