SCR_EditorActionList {
 m_Actions {
  EXPG_AddGarrisonContextAction "{B8B4BC59FA904E70}" {
   m_Info SCR_UIInfo "{14A891122FEC4B71}" {
    Name "EXPBG Add Garrison"
    Description "Choose an infantry squad to occupy this building."
    Icon "{21BAFC03CB14EAD3}UI/Textures/Editor/ContextMenu/ContextAction_BaseSupply.edds"
   }
   m_iOrder 205
   m_bIsServer 0
   m_Browser SCR_EditorContentBrowserDisplayConfig "{F5E92569ABAB4A63}" : "{A67E2D7288844EAF}Configs/Editor/ContentBrowser/EXPG_Infantry.conf" {
   }
  }
 }
}
