PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPAS {
   Configurations {
    EntityPersistenceConfig "{CB17D8B988F447E2}" : "{CE9825D2D58F4B6C}Configs/Systems/Persistence/Configuration/EXPAS/AmbientModule.conf" {
     Collection "{6624C4351F719B74}"
    }
    EntityPersistenceConfig "{5036E303CA1043D7}" : "{7FA3A0886728435A}Configs/Systems/Persistence/Configuration/EXPAS/RadioModule.conf" { Collection "{6624C4351F719B74}" }
    EntityPersistenceConfig "{26CD7194643D4BAA}" : "{394A4796D8124B15}Configs/Systems/Persistence/Configuration/EXPAS/CrowdModule.conf" { Collection "{6624C4351F719B74}" }
    EntityPersistenceConfig "{7B5C850366EA4FDA}" : "{45BECE2ED7C54809}Configs/Systems/Persistence/Configuration/EXPAS/TVModule.conf" { Collection "{6624C4351F719B74}" }
    EntityPersistenceConfig "{48EF1A93F15BCBA0}" : "{56AD3B1D2B39383F}Configs/Systems/Persistence/Configuration/EXPAS/SoundModule.conf" { Collection "{6624C4351F719B74}" }
   }
  }
 }
}
