PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPUS {
   Configurations {
    StatePersistenceConfig "{FCFCA79D4D45EDF8}" {
     Collection "{6586D01E488CA578}"
     SelfDelete 0
     Serializer EUS_ScriptPersistenceSerializer "{1BD2B29B6B010E7B}" {
     }
    }
   }
  }
 }
 PersistentStates + {
  EUS_ScriptPersistenceState "{2FD6B45F174EE0D4}" {
  }
 }
}
