EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{C6EA2353B5CC4E43}" {
  EntityClass "EAS_CrowdModule"
 }
 Priority 20001
 ParentHandling "Ignore always"
 EntitySerializer EAS_CrowdModuleSerializer "{E78152F12AC945B0}" {}
}
