EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{2101F6D7FD954150}" {
  EntityClass "EAS_RadioModule"
 }
 Priority 20000
 ParentHandling "Ignore always"
 EntitySerializer EAS_RadioModuleSerializer "{00CC8E010462498E}" {
 }
}
