EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{EEF5D167B3436A9B}" {
  EntityClass "EAS_SoundModule"
 }
 Priority 20001
 ParentHandling "Ignore always"
 EntitySerializer EAS_SoundModuleSerializer "{897688E93794461E}" {}
}
