EntityPersistenceConfig : "{9BD50C74BF89F2F5}Configs/Systems/Persistence/Configuration/Editor/EditableEntity.conf" {
 Rule EntityClassPersistenceConfigRule "{CD3029B2E3074E94}" {
  EntityClass "EAS_TVModule"
 }
 Priority 20001
 ParentHandling "Ignore always"
 EntitySerializer EAS_TVModuleSerializer "{0355918B23784E90}" {}
}
