PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPGR {
   Configurations {
    EntityPersistenceConfig "{3A7F1426908BF0D4}" : "{840DC0BF687F0F0D}Configs/Systems/Persistence/Configuration/EXPGR/RandomGarrison.conf" {
     Collection "{6624C4351F719B74}"
    }
   }
  }
 }
}
