SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SCR_GarbageSystem "{5F10E7EA29B0EDEC}" {
   ProcessingInterval 30
   ProcessingIterationsMax 20
   Rules {
    EntityClassGarbageRule "{60713063DB480AC7}" {
     OnlyDestroyed 1
     PlayerDistance 80
     PlayerLifetimeEffect Pause
    }
    EntityClassGarbageRule "{60713063F62751A3}" {
     OnlyDestroyed 1
     Lifetime 3600
    }
   }
  }
 }
}