StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{F873648171624059}" {
   Id "EXPBG-CacheZone_Description"
   Target_en_us "AI cache zone and owned-casualty cleanup. M.Pac and K.Edgar."
   Author "M.Pac and K.Edgar"
  }
  CustomStringTableItem "{B2780394F82C46D1}" {
   Id "EXPBG-CacheZone_Name"
   Target_en_us "EXPBG AI Cache Zone"
   Author "M.Pac and K.Edgar"
  }
  CustomStringTableItem "{B462AC315D908000}" {
   Id "EXPBG-OptimizerController_Description"
   Target_en_us "Global controls for Unit Caching zones only. Enable all, disable all, or safely prepare all AI for saving."
   Author "M.Pac and K.Edgar"
  }
  CustomStringTableItem "{B462AC315D908001}" {
   Id "EXPBG-OptimizerController_Name"
   Target_en_us "EXPBG UNIT CACHING CONTROLLER"
   Author "M.Pac and K.Edgar"
  }
 }
}
