PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPSR {
   Configurations {
    EntityPersistenceConfig "{42AC5C22AE9D981D}" : "{521379DDE1B6181F}Configs/Systems/Persistence/Configuration/EXPSR/SurrenderModule.conf" {
     Collection "{6624C4351F719B74}"
    }
   }
  }
 }
}
