PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EXPSR {
   Configurations {
    EntityPersistenceConfig "{42AC5C22AE9D981D}" : "{521379DDE1B6181F}Configs/Systems/Persistence/Configuration/EXPSR/SurrenderModule.conf" {
     Collection "{6624C4351F719B74}"
    }
    StatePersistenceConfig "{438CEF17F4C9AF45}" {
     Collection "{6586D01E488CA578}"
     SelfDelete 0
     Serializer ESR_OverridesSerializer "{C9ADAC18D15A7744}" {
     }
    }
   }
  }
 }
 PersistentStates + {
  ESR_OverridesState "{336619E1EF808904}" {
  }
 }
}
