PersistenceSystemConfig {
 Configurations + {
  PersistenceConfigGroup EGS {
   Configurations {
    StatePersistenceConfig "{EDFD751D708EE6B5}" {
     Collection "{6586D01E488CA578}"
     SelfDelete 0
     Serializer EGS_SettingsSerializer "{3B05898691531DA4}" {
     }
    }
   }
  }
 }
 PersistentStates + {
  EGS_SettingsState "{99EE9E794E205529}" {
  }
 }
}
