SCR_EditableEntityCore {
 m_EntityLabels + {
  SCR_EditableEntityCoreLabelSetting { m_Info SCR_UIInfo { Name "War sound effects" } m_LabelType EAS_WAR_EFFECTS m_LabelGroupType EAS_SOUND_TYPE m_bFilterEnabled 1 }
  SCR_EditableEntityCoreLabelSetting { m_Info SCR_UIInfo { Name "War mixes" } m_LabelType EAS_WAR_MIX m_LabelGroupType EAS_SOUND_TYPE m_bFilterEnabled 1 }
  SCR_EditableEntityCoreLabelSetting { m_Info SCR_UIInfo { Name "Radio transmissions" } m_LabelType EAS_RADIO m_LabelGroupType EAS_SOUND_TYPE m_bFilterEnabled 1 }
  SCR_EditableEntityCoreLabelSetting { m_Info SCR_UIInfo { Name "Crowd" } m_LabelType EAS_CROWD m_LabelGroupType EAS_SOUND_TYPE m_bFilterEnabled 1 }
  SCR_EditableEntityCoreLabelSetting { m_Info SCR_UIInfo { Name "Sound effects" } m_LabelType EAS_SOUND_EFFECTS m_LabelGroupType EAS_SOUND_TYPE m_bFilterEnabled 1 }

  SCR_EditableEntityCoreLabelSetting "{E5CFC52679245A1C}" {
   m_Info SCR_UIInfo "{55A78BB4015396F1}" {
    Name "EXPBG"
    Description "EXPBG Ambient Sounds"
    Icon "{C5A11E2DC4604AA0}UI/Textures/EXPBG/EXPBG_Badge_UI.edds"
   }
   m_LabelType EAS_BRAND
   m_LabelGroupType TRAIT
   m_bFilterEnabled 0
  }
 }
 m_LabelGroupSettings + {
  SCR_EditableEntityCoreLabelGroupSetting "{710F88BBF4BD42B2}" {
   m_Info SCR_UIInfo { Name "EXPBG Sounds" }
   m_Order 24
   m_LabelGroupType EAS_SOUND_TYPE
   m_ConditionalLabel ENTITYTYPE_SYSTEM
  }
 }
}
